version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directories: "/*"
    schedule:
      interval: "daily"
    # Disable version updates for npm dependencies (we only want security updates)
    open-pull-requests-limit: 0
